### ISSUE TITLE
Please enable Github discussion

### ISSUE THREAD

**Issue by iahung2** [dbsoft/dwindows#11]
Everyone has a github account could join the forum and start discussing immediately.

**Comment by dbsoft** [comment]
Well, I use my forum for discussion, I am not against enabling it... but what does it allow?  I have not seen that before on github.

**Comment by iahung2** [comment]
> Well, I use my forum for discussion, I am not against enabling it... but what does it allow? I have not seen that before on github.

The benefit of Github Discussions is it's part of Github so anyone has a Github account could join and start discussing immediately without having to leave Github. An external forum doesn't have this advantage as it requires additional registration  step.
