### ISSUE TITLE
Remove support for Cygwin on `dwcompat`

### ISSUE THREAD

**Issue by iahung2** [dbsoft/dwindows#14]
Support for Cygwin has been removed but on `dwcompat` there are still various references to Cygwin.

**Comment by dbsoft** [comment]
I don't think those should be removed, dwcompat is a support library that can be used outside of Dynamic Windows, it is non UI related support routines.

**Comment by iahung2** [comment]
> I don't think those should be removed, dwcompat is a support library that can be used outside of Dynamic Windows, it is non UI related support routines.

I don't know that this library is intended to use as a generic compatible layer. I'm sorry.

**Comment by dbsoft** [comment]
No need to be sorry, I am glad you are looking though it!  dwcompat is a library I use in some of my apps to help them function the same way regardless of what platform they are running on.  It generally helps with locating files in the file system and seeing what filesystems are available. It is not directly tied to Dynamic Windows other than that I use it in my Dynamic Windows apps.  Mark Hessling used Dynamic Windows with his Regina REXX language to create cross platform UIs, and REXX has its own methods of dealing with files, so he does not require dwcompat so the library is optional. I have use dwcompat in some apps that don't use Dynamic Windows or even a graphical interface at all.
