### ISSUE TITLE
More abstraction is needed

### ISSUE THREAD

**Issue by iahung2** [dbsoft/dwindows#19]
### Discussed in https://github.com/dbsoft/dwindows/discussions/17

<div type='discussions-op-text'>

<sup>Originally posted by **iahung2** September 22, 2023</sup>
Take IUP library as a reference: https://sourceforge.net/projects/iup/files/3.30/Windows%20Libraries/Dynamic/

You can't see any platform specific macros on the headers. Everything is abstracted nicely. `dw.h` instead is a gigantic header with full of platform specific macros. The constants and structs are also varied on each platforms (e.g: GTK vs Win32).</div>

**Comment by dbsoft** [comment]
Well, part of the idea originally anyway was it is a native interface... so you should be able to access platform specifics if you want to.... but at the same time be able to write code that can run on any supported platform.  

I could have chosen to abstract everything with opaque types so you couldn't accidentally do something you shouldn't, but I wanted to give the developers to do things natively if the library didn't provide that support in a platform specific #ifdef

**Comment by iahung2** [comment]
This architecture will cause you a great deal of difficulty when making the bindings for other languages. You will find out that the IUP library is designed to make it easy to make bindings for other languages from the beginning.

**Comment by iahung2** [comment]
@dbsoft Might I suggest you to make a more abstracted version of `dwindows`? You can't change the current library due to compatibility with old code. What about adding an abstracted wrapper of the current library? Name it `dwindows.h` and `dwindows.dll`. It will wrap `dw.h` and `dw.dll`. You already have `dwcompat.h` and `dwcompat.dll` anyway. You have also wrapped it to be C++ friendly with `dw.hpp`. It will be much easier to make bindings for other languages with the wrapper library.
