### ISSUE TITLE
Documentation is almost non-existent!

### ISSUE THREAD

**Issue by iahung2** [dbsoft/dwindows#21]
There is only API doc on http://dbsoft.org/dw_help.php but according to http://dwindows.netlabs.org/ it's for version 2.4, which is an ancient version as the current version is 3.3.

**Comment by dbsoft** [comment]
The documentation on dbsoft.org is current... I don't have access to change the information on that main netlabs page which is why it is outdated, the wiki on netlabs has up-to date information.
