### ISSUE TITLE
Building on MSYS2 (MinGW) is broken

### ISSUE THREAD

**Issue by iahung2** [dbsoft/dwindows#8]
I inspected `configure.ac` and I found it has support for MSYS2 (`mingw32` target) even though it will use GTK by default. But the support for MSYS2 seems to be very broken.

Please have a look at #7. I have to edit `configure.ac` to comment out `check_pthreads="yes"` (yes, I know it's an ugly hack). The configuration is fine now but when I build the code, so many problems arise.

p/s: I know `dwindows` has `makefile.mingw` but I think I should inform you about this.

**Comment by dbsoft** [comment]
I do not use configure when building and testing with mingw32/64... I use the mingw makefile you referenced and it works for me. Why do you need to use configure?

**Comment by iahung2** [comment]
> I do not use configure when building and testing with mingw32/64... I use the mingw makefile you referenced and it works for me. Why do you need to use configure?

If there is a configure script it's normal to go with it first. I took time before I discovered `makefile.mingw` and I think a lot of people is like me. Frankly speaking I have no needs for the configure script since I have `makefile.mingw` already working for me. But after a quick look at `dw.h` I found it's supported to build `dwindows` with GTK even on Windows so I want to explore it.

**Comment by iahung2** [comment]
Please consider removing `cygwin` and `mingw32` targets from `configure.ac` as they are actually not supported and not working: #9

**Comment by dbsoft** [comment]
Will do!

**Comment by dbsoft** [comment]
Ok, cygwin/ming support removed from configure so closing this.
